name: weathapp
description: A weather project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Custom packages
  easix: ^1.0.1
  talker_dio_logger: ^2.3.1

  # bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # json
  json_annotation: ^4.8.1

  # map
  geolocator: ^10.1.0

  connectivity_plus: ^5.0.1
  dio: ^5.3.3
  get_it: ^7.6.4
  go_router: ^12.0.0
  intl: ^0.18.1
  flutter_hooks: ^0.20.3
  animate_do: ^3.1.2
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  equatable: ^2.0.5
  lottie: ^2.7.0
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1

flutter:
  #  generate: true
  uses-material-design: true

  assets:
    - .env

flutter_native_splash:
  color: "#FFE147"
  image: assets/icon.png
  android: true
  ios: false
  android_12:
    color: "#FFE147"
    icon_background_color: "#FFE147"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 25
